booking/urls.py
from django.urls import path
from .views import *

app_name = 'booking'

urlpatterns = [
    path('', OrganisationListView.as_view(), name='organisation-list'),
    path('booking/<int:pk>/<str:slug>/', OrganisationDetailView.as_view(), name='organisation-detail'),
]

booking_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
    path('<int:pk>/<str:slug>/user/register/', user_views.RegisterFormView.as_view(), name='register'),
    path('organisation/', include('organisations.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/login.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import (
    RegisterFormView,
)

app_name = 'users'

urlpatterns = []

booking/models.py
from django.db import models

from organisations.models import Organisation, OpeningHour

# Create your models here.
class Booking(models.Model):
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=8)
    booked_at = models.DateTimeField()
    organisation = models.ForeignKey(
        Organisation,
        on_delete=models.CASCADE,
        blank=True
    )

    def __str__(self):
        return str((self.email, self.organisation.name))

booking/forms.py
from django import forms

from organisations.models import Booking


class BookingCreateForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ('booked_at', 'email', 'phone')

booking/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from organisations.models import Organisation, OpeningHour

from datetime import time

# Create your views here.

class OrganisationListView(ListView):
    model = Organisation
    template_name = 'booking/organisation_list.html'


class OrganisationDetailView(DetailView):
    model = Organisation
    template_name = 'booking/organisation_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        opening_hours = OpeningHour.objects.filter(organisation=context['object'])
        context['opening_hours'] = {}
        for day in OpeningHour.DayChoices:
            context['opening_hours'][day.name] = opening_hours.filter(day=day)
        context['table_hours'] = [str(x).zfill(2) for x in range(0, 24, 1)]
        context['table_minutes'] = [str(x).zfill(2) for x in range(0, 60, 15)]
        return context
    

booking/templates/booking/organisation_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ object.name }} - Booking</h1>
    <hr>
    <div class="row">
        <div class="col-md-12 card">
            <div class="row">
                <div class="col">
                    <p>BESKRIVELSE</p>
                    <hr>
                    {% include "organisations/includes/opening_hours.html" %}
                </div>
                {% if object.image %}
                    <div class="col-md-8">
                        <img src="#" alt="Organisations bygning">
                    </div>
                {% endif %}
            </div>
        </div> 
    </div>

    <div class="row mt-4">
        <div class="col card">
            <h2>Book her!</h2>
            <hr>
            <table>
                <tbody>
                    {% for minute in table_minutes %}
                        <tr>
                            {% for hour in table_hours %}
                                <td>{{ hour }}:{{ minute }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

booking/templates/booking/organisation_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Firmaer</h1>
<hr>

<div class="row">
    {% for org in object_list %}
        <div class="col-md-4 card">
            <h4><a href="{% url 'booking:organisation-detail' org.pk org.slug %}">{{ org.name }}</a></h4>
            <div class="row">
                <div class="col-md-6">
                    <img src="#" alt="IMAGE">
                </div>
                <div class="col-md-6">
                    <p>Adresse: {{ org.address }}</p>
                    <p>Tlf: {{ org.phone }}</p>
                    {% if org.website %}
                        <p>Website: <a href="{{ org.website }}">{{ org.website }}</a></p>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

booking/templates/booking/temp_home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Hello world!</h1>
{% endblock content %}