booking_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
    path('<int:pk>/<str:slug>/user/register/', user_views.RegisterFormView.as_view(), name='register'),
    path('organisation/', include('organisations.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/login.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organisations/urls.py
from django.urls import path
from .views import (
    register,
    OrganisationDetailView,
    CreateOpeningFormView,
    OpeningHourDeleteView,
)

app_name = 'organisations'

urlpatterns = [
    path('register/', register, name='register'),
    path('<int:pk>/<str:slug>/', OrganisationDetailView.as_view(), name='detail'),
    path('<int:pk>/<str:slug>/opening-hours/', CreateOpeningFormView.as_view(), name='opening-hours-create'),
    path('<int:org_id>/<str:slug>/opening-hours/<int:pk>/delete', OpeningHourDeleteView.as_view(), name='opening-hours-delete'),
]

users/urls.py
from django.urls import path

from .views import (
    RegisterFormView,
)

app_name = 'users'

urlpatterns = []

templates/includes/navigation/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand mr-4" href="/">Django Booking</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarToggle">
    <div class="navbar-nav mr-auto">
      <a class="nav-item nav-link" href="/">Home</a>
      <a class="nav-item nav-link" href="#">About</a>
      {% comment %} <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Dropdown
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li> {% endcomment %}
    </div>
    <!-- Navbar Right Side -->
    <div class="navbar-nav">
    {% if user.is_authenticated %}
      {% if user.profile.organisation %}
        <a class="nav-item nav-link" href="{% url 'organisations:detail' user.profile.organisation.pk user.profile.organisation.slug %}">{{ user.profile.organisation.name }}</a>
      {% endif %}
      <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
    {% else %}
      <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
      <a class="nav-item nav-link" href="{% url 'organisations:register' %}">Register</a>
    {% endif %}
    </div>
  </div>
</nav>


{% comment %} <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>

      {% comment %} <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

      {% comment %} <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>

    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Login</a>
      </li>
    </ul>

    {% comment %} <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

  </div>
</nav> {% endcomment %}