booking_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
    path('<int:pk>/<str:slug>/user/register/', user_views.RegisterFormView.as_view(), name='register'),
    path('organisation/', include('organisations.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/login.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organisations/urls.py
from django.urls import path
from .views import (
    register,
    OrganisationDetailView,
    CreateOpeningFormView,
    OpeningHourDeleteView,
)

app_name = 'organisations'

urlpatterns = [
    path('register/', register, name='register'),
    path('<int:pk>/<str:slug>/', OrganisationDetailView.as_view(), name='detail'),
    path('<int:pk>/<str:slug>/opening-hours/', CreateOpeningFormView.as_view(), name='opening-hours-create'),
    path('<int:org_id>/<str:slug>/opening-hours/<int:pk>/delete', OpeningHourDeleteView.as_view(), name='opening-hours-delete'),
]

users/urls.py
from django.urls import path

from .views import (
    RegisterFormView,
)

app_name = 'users'

urlpatterns = []

organisations/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError

from django.utils.text import slugify

import re, datetime

def validate_is_phonenumber(num:int) -> bool:
    if isinstance(num, int):
        return len(str(num)) == 8
    return False


def validateTimeFormInput(time) -> bool:
    regex = re.compile(r'^[0-2]\d[:][0-5]\d([:][0-5]\d)?$')
    if not re.match(regex, str(time)):
        raise ValidationError('Tidsinput skal overholde følgende format: 00:00')


# Create your models here.
class Organisation(models.Model):
    name = models.CharField(max_length=255)
    phone = models.IntegerField(validators=[validate_is_phonenumber])
    slug = models.SlugField(
        max_length=255,
        blank=True,
    )
    address = models.CharField(
        max_length=255,
    )
    website = models.CharField(
        max_length=255,
        default=None,
        null=True
    )
    image = models.ImageField(
        default=None,
        upload_to='organisations/',
        null=True
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class OpeningHour(models.Model):
    class DayChoices(models.TextChoices):
        MONDAY = (0, 'Mandag')
        TUESDAY = (1, 'Tirsdag')
        WEDNESDAY = (2, 'Onsdag')
        THURSDAY = (3, 'Torsdag')
        FRIDAY = (4, 'Fredag')
        SATURDAY = (5, 'Lørdag')
        SUNDAY = (6, 'Søndag')

    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    day = models.CharField(max_length=1, choices=DayChoices.choices, default=None)
    time_open = models.TimeField(default=None, validators=[validateTimeFormInput])
    working_time = models.CharField(max_length=255, validators=[validateTimeFormInput])
    
    @property
    def get_day(self):
        return self.get_day_display()

    @property
    def get_closing_hours(self):
        time_open_hours, time_open_minutes, *_ = str(self.time_open).split(':')
        time_open_delta = datetime.timedelta(hours=int(time_open_hours), minutes=int(time_open_minutes))
        closing_time = str(time_open_delta + datetime.timedelta(minutes=int(self.working_time)))
        
        if closing_time[1] == ':':
            closing_time = "0" + closing_time
        time_close_hours, time_close_minutes, *_ = closing_time.split(':')
        return datetime.time(hour=int(time_close_hours), minute=int(time_close_minutes))

    def __str__(self):
        return f'{self.organisation.name} ({self.day}, {self.time_open}, {self.working_time})'
    

users/models.py
from django.db import models

from django.contrib.auth.models import User


class RoleManager(models.Manager):
    def get_all_roles(self):
        return self.all()

class Role(models.Model):
    objects = RoleManager()

    name = models.CharField(max_length=255, unique=True)
    display_name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(
        "organisations.Organisation",
        on_delete=models.SET_DEFAULT,
        default=None,
        null=True
    )
    role = models.ForeignKey(
        Role,
        on_delete=models.SET_NULL,
        null=True
    )

    @property
    def full_name(self):
        "Returns the person's full name."
        return f'{self.user.first_name} {self.user.last_name}'

    def __str__(self):
        return f"{self.user.username}'s Profile"

organisations/forms.py
from django import forms
from django.forms import ValidationError
from django.utils.translation import gettext as _
from .models import Organisation, OpeningHour


class OrganisationRegisterForm(forms.ModelForm):
    phone = forms.IntegerField(required=False)

    def clean(self):
        phone = self.cleaned_data.get('phone')
        if len(str(phone)) != 8:
            raise ValidationError(_('Indtast et gyldigt telefon nummer'))
        return self.cleaned_data

    class Meta:
        model = Organisation
        fields = ('name', 'address', 'phone')


# DAY_CHOICES = (
#     ('', '----'),
#     (0, 'Mandag'),
#     (1, 'Tirsdag'),
#     (2, 'Onsdag'),
#     (3, 'Torsdag'),
#     (4, 'Fredag'),
#     (5, 'Lørdag'),
#     (6, 'Søndag'),
# )

class OpeningHourCreateForm(forms.ModelForm):
    day = forms.ChoiceField(choices=OpeningHour.DayChoices.choices)
    day.widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = OpeningHour
        fields = ('day', 'time_open', 'working_time')

        widgets = {
            'time_open': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'eks. 08:15'}),
            'working_time': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'eks. 16:00' }),
        }


class OpeningHourDeleteForm(forms.ModelForm):
    day = forms.ChoiceField(choices=OpeningHour.DayChoices.choices)
    day.widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = OpeningHour
        fields = ('day', 'time_open')

        widgets = {
            'time_open': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'eks. 08:15'}),
        }

organisations/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import DetailView, FormView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from users.forms import UserRegisterForm
from .forms import OrganisationRegisterForm, OpeningHourCreateForm
from .models import Organisation, OpeningHour
from users.models import Role

from access_rules import (
    UserInOrganisationMixin,
    UserIsOrganisationLeaderMixin,
    UserIsOpeningHourLeaderMixin
)

import datetime

# Create your views here.
class OrganisationDetailView(LoginRequiredMixin, UserInOrganisationMixin, DetailView):
    model = Organisation

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        opening_hours = OpeningHour.objects.filter(organisation=context['organisation'])
        context['opening_hours'] = {}
        for day in OpeningHour.DayChoices:
            context['opening_hours'][day.name] = opening_hours.filter(day=day)
        return context
    


def register(request):
    if request.method == 'POST':
        o_form = OrganisationRegisterForm(request.POST)
        u_form = UserRegisterForm(request.POST)
        if o_form.is_valid() and u_form.is_valid():
            roles = Role.objects.get_all_roles()
            organ = o_form.save()
            user = u_form.save()
            user.profile.organisation = organ
            user.profile.role = roles.get(name='Leader')
            user.profile.save()
            messages.success(request, 'Account created successfully.')
            return redirect(reverse('login'))
    else:
        o_form = OrganisationRegisterForm()
        u_form = UserRegisterForm()
    context = {
        'forms': {
            'u_form': u_form,
            'o_form': o_form,
        }
    }
    return render(request, 'organisations/register.html', context=context)



class CreateOpeningFormView(LoginRequiredMixin, UserIsOrganisationLeaderMixin, FormView):
    template_name = 'organisations/openinghour_create.html'
    form_class = OpeningHourCreateForm
    
    def get_success_url(self):
        return reverse('organisations:opening-hours-create', kwargs={'pk': self.kwargs.get('pk'), 'slug': self.kwargs.get('slug')})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        opening_hours = OpeningHour.objects.filter(organisation__id=self.kwargs.get('pk'))
        context['opening_hours'] = {}
        for day in OpeningHour.DayChoices:
            context['opening_hours'][day.name] = opening_hours.filter(day=day).order_by('time_open')
        return context
    
    def form_valid(self, form):
        time_open = str(form.cleaned_data["time_open"])
        time_open_hours, time_open_minutes, *_ = time_open.split(':')
        time_open_delta = datetime.timedelta(hours=int(time_open_hours), minutes=int(time_open_minutes))

        working_time = str(form.cleaned_data["working_time"])
        working_hours, working_minutes, *_ = working_time.split(':')
        working_time_delta = datetime.timedelta(hours=int(working_hours), minutes=int(working_minutes))

        time_diff = working_time_delta - time_open_delta
        
        self.object = form.save(commit=False)
        self.object.organisation = Organisation.objects.get(pk=self.kwargs.get('pk'))
        self.object.working_time = int(time_diff.total_seconds()/60)
        self.object.save()
        return redirect(self.get_success_url())


class OpeningHourDeleteView(LoginRequiredMixin, UserIsOpeningHourLeaderMixin, DeleteView):
    model = OpeningHour

    def get_success_url(self):
        return reverse('organisations:opening-hours-create', kwargs={'pk': self.kwargs.get('org_id'), 'slug': self.kwargs.get('slug')})

organisations/templates/organisations/openinghour_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Slet åbningstid</h1>
<hr>
<div class="row card">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <h2>Er du sikker på du vil slette denne tid?</h2>
            <p>{{ object.get_day_display }}, {{ object.time_open }} - {{ object.get_closing_hours }}</p>
        </fieldset>
        <div class="form-group">
            <button type="submit" class="btn btn-danger">Ja, slet tid</button>
            <a href="{% url 'organisations:opening-hours-create' object.organisation.id object.organisation.slug %}" class="btn btn-secondary">Nej, gå tilbage</a>
        </div>
    </form>
</div>
{% endblock content %}

organisations/templates/organisations/openinghour_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>Åbningstider</h1>
    <a href="{% url 'organisations:detail' view.kwargs.pk view.kwargs.slug %}" class="btn btn-info">Tilbage til oversigt</a>
    <hr>
    <div class="row">
        <div class="col-md-7 card">
            <h4>Opret åbningstid</h4>
            <hr>
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form.errors }}
                    {{ form.non_field_errors }}
                    <div class="row">
                        <div class="col">
                            <label for="{{ form.day.id_for_label }}">Dag</label>
                        </div>
                        <div class="col">
                            <label for="{{ form.time_open.id_for_label }}">Åbningstid</label>
                        </div>
                        <div class="col">
                            <label for="{{ form.working_time.id_for_label }}">Lukketid</label>
                        </div>
                        <div class="col-md-1"></div>
                    </div>

                    <div class="row">
                        <div class="col">
                            {{ form.day }}
                        </div>
                        <div class="col">
                            {{ form.time_open }}
                        </div>
                        <div class="col">
                            {{ form.working_time }}
                        </div>
                        <div class="col-md-1">
                            <input type="submit" class="btn btn-success btn-sm" value="+">
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>

        <div class="col-md-4 offset-md-1 card">
            <h4>Nuværende åbningstider</h4>
            <hr>
            {% include "organisations/includes/opening_hours.html" %}
        </div>
    </div>
{% endblock content %}

organisations/templates/organisations/openinghours_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>Åbningstider</h1>
    <hr>
    <div class="row">
        <div class="col-md-7 card">
            <h4>Opret åbningstid</h4>
            <hr>
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form.errors }}
                    {{ form.non_field_errors }}
                    <div class="row">
                        <div class="col">
                            <label for="{{ form.day.id_for_label }}">Dag</label>
                        </div>
                        <div class="col">
                            <label for="{{ form.time_open.id_for_label }}">Åbningstid</label>
                        </div>
                        <div class="col">
                            <label for="{{ form.working_time.id_for_label }}">Lukketid</label>
                        </div>
                        <div class="col-md-1"></div>
                    </div>

                    <div class="row">
                        <div class="col">
                            {{ form.day }}
                        </div>
                        <div class="col">
                            {{ form.time_open }}
                        </div>
                        <div class="col">
                            {{ form.working_time }}
                        </div>
                        <div class="col-md-1">
                            <input type="submit" class="btn btn-success btn-sm" value="+">
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>

        <div class="col-md-4 offset-md-1 card">
            <h4>Nuværende åbningstider</h4>
            <hr>
            {% for opening_hour in opening_hours %}
                <ul>
                    <li>
                        {{ opening_hour.get_day_display }}: {{ opening_hour.time_open }} - {{ opening_hour.get_closing_hours }}
                    </li>
                </ul>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

organisations/templates/organisations/organisation_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <hr>
    <!-- Organisation overview -->
    <div class="row mb-5 ">
        <div class="col-md-5 card">
            <div class="">
                <div class="">
                    <h4>{{ object.name }}</h4>
                    {% if user.profile.role.name == 'Leader' %}
                        <a href="{% url 'organisations:opening-hours-create' object.pk object.slug %}" class="btn btn-sm btn-primary">Indstillinger</a>
                    {% endif %}
                </div>
                {% if object.website %}
                    <p>Hjemmeside: <a href="{{ object.website }}">{{ object.website }}</a></p>
                {% endif %}
                {% if object.address %}
                    <p>Adresse: {{ object.address }}</p>
                {% endif %}
                <hr>
                {% include "organisations/includes/opening_hours.html" %}
            </div>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-6 card">
            <h4>Indstillinger</h4>
        </div>
    </div>
    <!-- Schedule creator/editor -->
    <!-- Schedule overview -->


    <!-- Employee account creation -->
    <!-- Employee overview -->
    <div class="row">
        <div class="col-md-10 mx-auto">
            <div class="card">
                <div class="employee-overview--navigation">
                    <h4>Medarbejder oversigt</h4>
                    <a href="{% url 'register' object.pk object.slug %}" class="btn btn-sm btn-primary">Opret ny</a>
                </div>
                <div class="" style="padding-top:16px;">
                    <table class="employee-overview--table-header" style="width:100%;">
                        <thead>
                            <tr>
                                <td>Fulde navn</td>
                                <td>Brugernavn</td>
                                <td>Rolle</td>
                                <td>Optaget</td>
                                <td>Oprettet</td>
                                {% if user.profile.role.name == 'Leader' %}
                                    <td>Værktøjer</td>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for profile in object.profile_set.all %}
                                <tr>
                                    <td>{{ profile.full_name }}</td>
                                    <td>{{ profile.user.username }}</td>
                                    <td>{{ profile.role|default:"Ingen" }}</td>
                                    <td>NYI</td>
                                    <td>{{ profile.user.date_joined|date:"d-m-Y" }}</td>
                                    {% if user.profile.role.name == 'Leader' %}
                                        <td>
                                            <a href="#" class="btn btn-sm btn-info">Rediger</a>
                                            <a href="#" class="btn btn-sm btn-danger">Slet</a>
                                        </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

organisations/templates/organisations/register.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <h1>Opret en konto</h1>
        <hr>
        <div class="row">
            <div class="col-md-6">
                <fieldset class="form-group">
                    <legend>Bruger information</legend>
                    {{ forms.u_form|crispy }}
                </fieldset>
            </div>
            <div class="col-md-6">
                <fieldset class="form-group">
                <legend>Firma information</legend>
                    {{ forms.o_form|crispy }}
                </fieldset>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Registrer konto</button>
        </div>
        <div>
            <small>Har du allerede en konto? <a href="{% url 'login' %}">Log ind her!</a></small>
        </div>
    </form>
{% endblock content %}